// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v4.0.0
// source: service.proto

package messaging

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type DropState int32

const (
	DropState_DROPPED  DropState = 0
	DropState_FLOATING DropState = 1
	DropState_PICKEDUP DropState = 2
)

// Enum value maps for DropState.
var (
	DropState_name = map[int32]string{
		0: "DROPPED",
		1: "FLOATING",
		2: "PICKEDUP",
	}
	DropState_value = map[string]int32{
		"DROPPED":  0,
		"FLOATING": 1,
		"PICKEDUP": 2,
	}
)

func (x DropState) Enum() *DropState {
	p := new(DropState)
	*p = x
	return p
}

func (x DropState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DropState) Descriptor() protoreflect.EnumDescriptor {
	return file_service_proto_enumTypes[0].Descriptor()
}

func (DropState) Type() protoreflect.EnumType {
	return &file_service_proto_enumTypes[0]
}

func (x DropState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DropState.Descriptor instead.
func (DropState) EnumDescriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

type RequestEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*RequestEvent_DropItem
	//	*RequestEvent_PressButton
	//	*RequestEvent_ExpressionButton
	//	*RequestEvent_PlayerConnect
	Event isRequestEvent_Event `protobuf_oneof:"event"`
}

func (x *RequestEvent) Reset() {
	*x = RequestEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestEvent) ProtoMessage() {}

func (x *RequestEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestEvent.ProtoReflect.Descriptor instead.
func (*RequestEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{0}
}

func (m *RequestEvent) GetEvent() isRequestEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *RequestEvent) GetDropItem() *RequestDropItem {
	if x, ok := x.GetEvent().(*RequestEvent_DropItem); ok {
		return x.DropItem
	}
	return nil
}

func (x *RequestEvent) GetPressButton() *PressButton {
	if x, ok := x.GetEvent().(*RequestEvent_PressButton); ok {
		return x.PressButton
	}
	return nil
}

func (x *RequestEvent) GetExpressionButton() *ExpressionButton {
	if x, ok := x.GetEvent().(*RequestEvent_ExpressionButton); ok {
		return x.ExpressionButton
	}
	return nil
}

func (x *RequestEvent) GetPlayerConnect() *RequestPlayerConnect {
	if x, ok := x.GetEvent().(*RequestEvent_PlayerConnect); ok {
		return x.PlayerConnect
	}
	return nil
}

type isRequestEvent_Event interface {
	isRequestEvent_Event()
}

type RequestEvent_DropItem struct {
	DropItem *RequestDropItem `protobuf:"bytes,1,opt,name=dropItem,proto3,oneof"`
}

type RequestEvent_PressButton struct {
	PressButton *PressButton `protobuf:"bytes,2,opt,name=pressButton,proto3,oneof"`
}

type RequestEvent_ExpressionButton struct {
	ExpressionButton *ExpressionButton `protobuf:"bytes,3,opt,name=expressionButton,proto3,oneof"`
}

type RequestEvent_PlayerConnect struct {
	PlayerConnect *RequestPlayerConnect `protobuf:"bytes,4,opt,name=playerConnect,proto3,oneof"`
}

func (*RequestEvent_DropItem) isRequestEvent_Event() {}

func (*RequestEvent_PressButton) isRequestEvent_Event() {}

func (*RequestEvent_ExpressionButton) isRequestEvent_Event() {}

func (*RequestEvent_PlayerConnect) isRequestEvent_Event() {}

type ResponseEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Event:
	//	*ResponseEvent_DropItem
	//	*ResponseEvent_PressButton
	//	*ResponseEvent_ExpressionButton
	//	*ResponseEvent_PlayerConnected
	//	*ResponseEvent_OtherPlayerConnected
	Event isResponseEvent_Event `protobuf_oneof:"event"`
}

func (x *ResponseEvent) Reset() {
	*x = ResponseEvent{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseEvent) ProtoMessage() {}

func (x *ResponseEvent) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseEvent.ProtoReflect.Descriptor instead.
func (*ResponseEvent) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{1}
}

func (m *ResponseEvent) GetEvent() isResponseEvent_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (x *ResponseEvent) GetDropItem() *ResponseDropItem {
	if x, ok := x.GetEvent().(*ResponseEvent_DropItem); ok {
		return x.DropItem
	}
	return nil
}

func (x *ResponseEvent) GetPressButton() *PressButton {
	if x, ok := x.GetEvent().(*ResponseEvent_PressButton); ok {
		return x.PressButton
	}
	return nil
}

func (x *ResponseEvent) GetExpressionButton() *ExpressionButton {
	if x, ok := x.GetEvent().(*ResponseEvent_ExpressionButton); ok {
		return x.ExpressionButton
	}
	return nil
}

func (x *ResponseEvent) GetPlayerConnected() *ResponsePlayerConnected {
	if x, ok := x.GetEvent().(*ResponseEvent_PlayerConnected); ok {
		return x.PlayerConnected
	}
	return nil
}

func (x *ResponseEvent) GetOtherPlayerConnected() *ResponseOtherPlayerConnected {
	if x, ok := x.GetEvent().(*ResponseEvent_OtherPlayerConnected); ok {
		return x.OtherPlayerConnected
	}
	return nil
}

type isResponseEvent_Event interface {
	isResponseEvent_Event()
}

type ResponseEvent_DropItem struct {
	DropItem *ResponseDropItem `protobuf:"bytes,1,opt,name=dropItem,proto3,oneof"`
}

type ResponseEvent_PressButton struct {
	PressButton *PressButton `protobuf:"bytes,2,opt,name=pressButton,proto3,oneof"`
}

type ResponseEvent_ExpressionButton struct {
	ExpressionButton *ExpressionButton `protobuf:"bytes,3,opt,name=expressionButton,proto3,oneof"`
}

type ResponseEvent_PlayerConnected struct {
	PlayerConnected *ResponsePlayerConnected `protobuf:"bytes,4,opt,name=playerConnected,proto3,oneof"`
}

type ResponseEvent_OtherPlayerConnected struct {
	OtherPlayerConnected *ResponseOtherPlayerConnected `protobuf:"bytes,5,opt,name=otherPlayerConnected,proto3,oneof"`
}

func (*ResponseEvent_DropItem) isResponseEvent_Event() {}

func (*ResponseEvent_PressButton) isResponseEvent_Event() {}

func (*ResponseEvent_ExpressionButton) isResponseEvent_Event() {}

func (*ResponseEvent_PlayerConnected) isResponseEvent_Event() {}

func (*ResponseEvent_OtherPlayerConnected) isResponseEvent_Event() {}

type RequestPlayerConnect struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charid int32 `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
}

func (x *RequestPlayerConnect) Reset() {
	*x = RequestPlayerConnect{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestPlayerConnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestPlayerConnect) ProtoMessage() {}

func (x *RequestPlayerConnect) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestPlayerConnect.ProtoReflect.Descriptor instead.
func (*RequestPlayerConnect) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{2}
}

func (x *RequestPlayerConnect) GetCharid() int32 {
	if x != nil {
		return x.Charid
	}
	return 0
}

type ResponsePlayerConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charid int32 `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Hair   int32 `protobuf:"varint,2,opt,name=hair,proto3" json:"hair,omitempty"`
	Skin   int32 `protobuf:"varint,3,opt,name=skin,proto3" json:"skin,omitempty"`
	Face   int32 `protobuf:"varint,4,opt,name=face,proto3" json:"face,omitempty"`
}

func (x *ResponsePlayerConnected) Reset() {
	*x = ResponsePlayerConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponsePlayerConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponsePlayerConnected) ProtoMessage() {}

func (x *ResponsePlayerConnected) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponsePlayerConnected.ProtoReflect.Descriptor instead.
func (*ResponsePlayerConnected) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{3}
}

func (x *ResponsePlayerConnected) GetCharid() int32 {
	if x != nil {
		return x.Charid
	}
	return 0
}

func (x *ResponsePlayerConnected) GetHair() int32 {
	if x != nil {
		return x.Hair
	}
	return 0
}

func (x *ResponsePlayerConnected) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

func (x *ResponsePlayerConnected) GetFace() int32 {
	if x != nil {
		return x.Face
	}
	return 0
}

type ResponseOtherPlayerConnected struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charid int32  `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Hair   int32  `protobuf:"varint,2,opt,name=hair,proto3" json:"hair,omitempty"`
	Skin   int32  `protobuf:"varint,3,opt,name=skin,proto3" json:"skin,omitempty"`
	Face   int32  `protobuf:"varint,4,opt,name=face,proto3" json:"face,omitempty"`
	State  int32  `protobuf:"varint,5,opt,name=state,proto3" json:"state,omitempty"`
	Pos    *Point `protobuf:"bytes,6,opt,name=pos,proto3" json:"pos,omitempty"`
}

func (x *ResponseOtherPlayerConnected) Reset() {
	*x = ResponseOtherPlayerConnected{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseOtherPlayerConnected) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseOtherPlayerConnected) ProtoMessage() {}

func (x *ResponseOtherPlayerConnected) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseOtherPlayerConnected.ProtoReflect.Descriptor instead.
func (*ResponseOtherPlayerConnected) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{4}
}

func (x *ResponseOtherPlayerConnected) GetCharid() int32 {
	if x != nil {
		return x.Charid
	}
	return 0
}

func (x *ResponseOtherPlayerConnected) GetHair() int32 {
	if x != nil {
		return x.Hair
	}
	return 0
}

func (x *ResponseOtherPlayerConnected) GetSkin() int32 {
	if x != nil {
		return x.Skin
	}
	return 0
}

func (x *ResponseOtherPlayerConnected) GetFace() int32 {
	if x != nil {
		return x.Face
	}
	return 0
}

func (x *ResponseOtherPlayerConnected) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

func (x *ResponseOtherPlayerConnected) GetPos() *Point {
	if x != nil {
		return x.Pos
	}
	return nil
}

type PressButton struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charid  int32 `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Button  int32 `protobuf:"varint,2,opt,name=button,proto3" json:"button,omitempty"`
	Pressed bool  `protobuf:"varint,3,opt,name=pressed,proto3" json:"pressed,omitempty"`
}

func (x *PressButton) Reset() {
	*x = PressButton{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PressButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PressButton) ProtoMessage() {}

func (x *PressButton) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PressButton.ProtoReflect.Descriptor instead.
func (*PressButton) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{5}
}

func (x *PressButton) GetCharid() int32 {
	if x != nil {
		return x.Charid
	}
	return 0
}

func (x *PressButton) GetButton() int32 {
	if x != nil {
		return x.Button
	}
	return 0
}

func (x *PressButton) GetPressed() bool {
	if x != nil {
		return x.Pressed
	}
	return false
}

type ExpressionButton struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Charid     int32 `protobuf:"varint,1,opt,name=charid,proto3" json:"charid,omitempty"`
	Expression int32 `protobuf:"varint,2,opt,name=expression,proto3" json:"expression,omitempty"`
}

func (x *ExpressionButton) Reset() {
	*x = ExpressionButton{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ExpressionButton) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExpressionButton) ProtoMessage() {}

func (x *ExpressionButton) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExpressionButton.ProtoReflect.Descriptor instead.
func (*ExpressionButton) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{6}
}

func (x *ExpressionButton) GetCharid() int32 {
	if x != nil {
		return x.Charid
	}
	return 0
}

func (x *ExpressionButton) GetExpression() int32 {
	if x != nil {
		return x.Expression
	}
	return 0
}

type RequestDropItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"` //0 mesos
	Count   int32  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	Owner   int32  `protobuf:"varint,3,opt,name=owner,proto3" json:"owner,omitempty"`
	Start   *Point `protobuf:"bytes,4,opt,name=start,proto3" json:"start,omitempty"`
	Invtype int32  `protobuf:"varint,6,opt,name=invtype,proto3" json:"invtype,omitempty"` // todo refactor to enum later
	Slotid  int32  `protobuf:"varint,7,opt,name=slotid,proto3" json:"slotid,omitempty"`
	Mapid   int32  `protobuf:"varint,8,opt,name=mapid,proto3" json:"mapid,omitempty"`
}

func (x *RequestDropItem) Reset() {
	*x = RequestDropItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RequestDropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestDropItem) ProtoMessage() {}

func (x *RequestDropItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestDropItem.ProtoReflect.Descriptor instead.
func (*RequestDropItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{7}
}

func (x *RequestDropItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *RequestDropItem) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *RequestDropItem) GetOwner() int32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *RequestDropItem) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *RequestDropItem) GetInvtype() int32 {
	if x != nil {
		return x.Invtype
	}
	return 0
}

func (x *RequestDropItem) GetSlotid() int32 {
	if x != nil {
		return x.Slotid
	}
	return 0
}

func (x *RequestDropItem) GetMapid() int32 {
	if x != nil {
		return x.Mapid
	}
	return 0
}

type ResponseDropItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Oid   int32  `protobuf:"varint,1,opt,name=oid,proto3" json:"oid,omitempty"`
	Id    int32  `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"` //0 mesos
	Start *Point `protobuf:"bytes,3,opt,name=start,proto3" json:"start,omitempty"`
	Owner int32  `protobuf:"varint,4,opt,name=owner,proto3" json:"owner,omitempty"`
	Mapid int32  `protobuf:"varint,5,opt,name=mapid,proto3" json:"mapid,omitempty"`
}

func (x *ResponseDropItem) Reset() {
	*x = ResponseDropItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDropItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDropItem) ProtoMessage() {}

func (x *ResponseDropItem) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDropItem.ProtoReflect.Descriptor instead.
func (*ResponseDropItem) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{8}
}

func (x *ResponseDropItem) GetOid() int32 {
	if x != nil {
		return x.Oid
	}
	return 0
}

func (x *ResponseDropItem) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ResponseDropItem) GetStart() *Point {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ResponseDropItem) GetOwner() int32 {
	if x != nil {
		return x.Owner
	}
	return 0
}

func (x *ResponseDropItem) GetMapid() int32 {
	if x != nil {
		return x.Mapid
	}
	return 0
}

type Point struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	X float32 `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y float32 `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
}

func (x *Point) Reset() {
	*x = Point{}
	if protoimpl.UnsafeEnabled {
		mi := &file_service_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_service_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_service_proto_rawDescGZIP(), []int{9}
}

func (x *Point) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *Point) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_service_proto protoreflect.FileDescriptor

var file_service_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x22, 0xa1, 0x02, 0x0a, 0x0c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x38, 0x0a, 0x08, 0x64,
	0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x48, 0x00, 0x52, 0x08, 0x64, 0x72, 0x6f,
	0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3a, 0x0a, 0x0b, 0x70, 0x72, 0x65, 0x73, 0x73, 0x42, 0x75,
	0x74, 0x74, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x65, 0x73, 0x73, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x73, 0x73, 0x42, 0x75, 0x74, 0x74, 0x6f,
	0x6e, 0x12, 0x49, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42,
	0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x10, 0x65, 0x78, 0x70, 0x72,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0d,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f,
	0x6e, 0x6e, 0x65, 0x63, 0x74, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x89,
	0x03, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x76, 0x65, 0x6e, 0x74,
	0x12, 0x39, 0x0a, 0x08, 0x64, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x48,
	0x00, 0x52, 0x08, 0x64, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65, 0x6d, 0x12, 0x3a, 0x0a, 0x0b, 0x70,
	0x72, 0x65, 0x73, 0x73, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x72, 0x65,
	0x73, 0x73, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x48, 0x00, 0x52, 0x0b, 0x70, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x49, 0x0a, 0x10, 0x65, 0x78, 0x70, 0x72, 0x65,
	0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x45, 0x78,
	0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x48, 0x00,
	0x52, 0x10, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42, 0x75, 0x74, 0x74,
	0x6f, 0x6e, 0x12, 0x4e, 0x0a, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x6d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48,
	0x00, 0x52, 0x0f, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74,
	0x65, 0x64, 0x12, 0x5d, 0x0a, 0x14, 0x6f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x27, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72,
	0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x48, 0x00, 0x52, 0x14, 0x6f, 0x74, 0x68,
	0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65,
	0x64, 0x42, 0x07, 0x0a, 0x05, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x22, 0x2e, 0x0a, 0x14, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65,
	0x63, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x22, 0x6d, 0x0a, 0x17, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x68, 0x61, 0x69,
	0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x04, 0x73, 0x6b, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61, 0x63, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x61, 0x63, 0x65, 0x22, 0xac, 0x01, 0x0a, 0x1c, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x4f, 0x74, 0x68, 0x65, 0x72, 0x50, 0x6c, 0x61, 0x79, 0x65,
	0x72, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x65, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68,
	0x61, 0x72, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x69, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x68, 0x61, 0x69, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x73, 0x6b, 0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x61,
	0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x66, 0x61, 0x63, 0x65, 0x12, 0x14,
	0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x73,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x22, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x6f,
	0x69, 0x6e, 0x74, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0x57, 0x0a, 0x0b, 0x50, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x12,
	0x16, 0x0a, 0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x62, 0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x73, 0x73,
	0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x70, 0x72, 0x65, 0x73, 0x73, 0x65,
	0x64, 0x22, 0x4a, 0x0a, 0x10, 0x45, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x42,
	0x75, 0x74, 0x74, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x63, 0x68, 0x61, 0x72, 0x69, 0x64, 0x12, 0x1e, 0x0a,
	0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0a, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0xbd, 0x01,
	0x0a, 0x0f, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x74, 0x65,
	0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x26, 0x0a,
	0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x69, 0x6e, 0x76, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x76, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x16, 0x0a, 0x06, 0x73, 0x6c, 0x6f, 0x74, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x6c, 0x6f, 0x74, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x69, 0x64,
	0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x69, 0x64, 0x22, 0x88, 0x01,
	0x0a, 0x10, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x72, 0x6f, 0x70, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x6f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x6f, 0x69, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x50, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x05, 0x73, 0x74, 0x61, 0x72, 0x74, 0x12, 0x14, 0x0a, 0x05,
	0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6f, 0x77, 0x6e,
	0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x61, 0x70, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x05, 0x6d, 0x61, 0x70, 0x69, 0x64, 0x22, 0x23, 0x0a, 0x05, 0x50, 0x6f, 0x69, 0x6e,
	0x74, 0x12, 0x0c, 0x0a, 0x01, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x78, 0x12,
	0x0c, 0x0a, 0x01, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x01, 0x79, 0x2a, 0x34, 0x0a,
	0x09, 0x44, 0x72, 0x6f, 0x70, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x0b, 0x0a, 0x07, 0x44, 0x52,
	0x4f, 0x50, 0x50, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0c, 0x0a, 0x08, 0x46, 0x4c, 0x4f, 0x41, 0x54,
	0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0c, 0x0a, 0x08, 0x50, 0x49, 0x43, 0x4b, 0x45, 0x44, 0x55,
	0x50, 0x10, 0x02, 0x32, 0x55, 0x0a, 0x0c, 0x4d, 0x61, 0x70, 0x6c, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x0c, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x73, 0x53, 0x74, 0x72,
	0x65, 0x61, 0x6d, 0x12, 0x17, 0x2e, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x1a, 0x18, 0x2e, 0x6d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x69, 0x6e, 0x67, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x28, 0x01, 0x30, 0x01, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_service_proto_rawDescOnce sync.Once
	file_service_proto_rawDescData = file_service_proto_rawDesc
)

func file_service_proto_rawDescGZIP() []byte {
	file_service_proto_rawDescOnce.Do(func() {
		file_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_service_proto_rawDescData)
	})
	return file_service_proto_rawDescData
}

var file_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_service_proto_goTypes = []interface{}{
	(DropState)(0),                       // 0: messaging.DropState
	(*RequestEvent)(nil),                 // 1: messaging.RequestEvent
	(*ResponseEvent)(nil),                // 2: messaging.ResponseEvent
	(*RequestPlayerConnect)(nil),         // 3: messaging.RequestPlayerConnect
	(*ResponsePlayerConnected)(nil),      // 4: messaging.ResponsePlayerConnected
	(*ResponseOtherPlayerConnected)(nil), // 5: messaging.ResponseOtherPlayerConnected
	(*PressButton)(nil),                  // 6: messaging.PressButton
	(*ExpressionButton)(nil),             // 7: messaging.ExpressionButton
	(*RequestDropItem)(nil),              // 8: messaging.RequestDropItem
	(*ResponseDropItem)(nil),             // 9: messaging.ResponseDropItem
	(*Point)(nil),                        // 10: messaging.Point
}
var file_service_proto_depIdxs = []int32{
	8,  // 0: messaging.RequestEvent.dropItem:type_name -> messaging.RequestDropItem
	6,  // 1: messaging.RequestEvent.pressButton:type_name -> messaging.PressButton
	7,  // 2: messaging.RequestEvent.expressionButton:type_name -> messaging.ExpressionButton
	3,  // 3: messaging.RequestEvent.playerConnect:type_name -> messaging.RequestPlayerConnect
	9,  // 4: messaging.ResponseEvent.dropItem:type_name -> messaging.ResponseDropItem
	6,  // 5: messaging.ResponseEvent.pressButton:type_name -> messaging.PressButton
	7,  // 6: messaging.ResponseEvent.expressionButton:type_name -> messaging.ExpressionButton
	4,  // 7: messaging.ResponseEvent.playerConnected:type_name -> messaging.ResponsePlayerConnected
	5,  // 8: messaging.ResponseEvent.otherPlayerConnected:type_name -> messaging.ResponseOtherPlayerConnected
	10, // 9: messaging.ResponseOtherPlayerConnected.pos:type_name -> messaging.Point
	10, // 10: messaging.RequestDropItem.start:type_name -> messaging.Point
	10, // 11: messaging.ResponseDropItem.start:type_name -> messaging.Point
	1,  // 12: messaging.MapleService.EventsStream:input_type -> messaging.RequestEvent
	2,  // 13: messaging.MapleService.EventsStream:output_type -> messaging.ResponseEvent
	13, // [13:14] is the sub-list for method output_type
	12, // [12:13] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_service_proto_init() }
func file_service_proto_init() {
	if File_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseEvent); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestPlayerConnect); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponsePlayerConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseOtherPlayerConnected); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PressButton); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ExpressionButton); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RequestDropItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDropItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_service_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Point); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_service_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*RequestEvent_DropItem)(nil),
		(*RequestEvent_PressButton)(nil),
		(*RequestEvent_ExpressionButton)(nil),
		(*RequestEvent_PlayerConnect)(nil),
	}
	file_service_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ResponseEvent_DropItem)(nil),
		(*ResponseEvent_PressButton)(nil),
		(*ResponseEvent_ExpressionButton)(nil),
		(*ResponseEvent_PlayerConnected)(nil),
		(*ResponseEvent_OtherPlayerConnected)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_service_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_service_proto_goTypes,
		DependencyIndexes: file_service_proto_depIdxs,
		EnumInfos:         file_service_proto_enumTypes,
		MessageInfos:      file_service_proto_msgTypes,
	}.Build()
	File_service_proto = out.File
	file_service_proto_rawDesc = nil
	file_service_proto_goTypes = nil
	file_service_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MapleServiceClient is the client API for MapleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MapleServiceClient interface {
	EventsStream(ctx context.Context, opts ...grpc.CallOption) (MapleService_EventsStreamClient, error)
}

type mapleServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMapleServiceClient(cc grpc.ClientConnInterface) MapleServiceClient {
	return &mapleServiceClient{cc}
}

func (c *mapleServiceClient) EventsStream(ctx context.Context, opts ...grpc.CallOption) (MapleService_EventsStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MapleService_serviceDesc.Streams[0], "/messaging.MapleService/EventsStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &mapleServiceEventsStreamClient{stream}
	return x, nil
}

type MapleService_EventsStreamClient interface {
	Send(*RequestEvent) error
	Recv() (*ResponseEvent, error)
	grpc.ClientStream
}

type mapleServiceEventsStreamClient struct {
	grpc.ClientStream
}

func (x *mapleServiceEventsStreamClient) Send(m *RequestEvent) error {
	return x.ClientStream.SendMsg(m)
}

func (x *mapleServiceEventsStreamClient) Recv() (*ResponseEvent, error) {
	m := new(ResponseEvent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MapleServiceServer is the server API for MapleService service.
type MapleServiceServer interface {
	EventsStream(MapleService_EventsStreamServer) error
}

// UnimplementedMapleServiceServer can be embedded to have forward compatible implementations.
type UnimplementedMapleServiceServer struct {
}

func (*UnimplementedMapleServiceServer) EventsStream(MapleService_EventsStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method EventsStream not implemented")
}

func RegisterMapleServiceServer(s *grpc.Server, srv MapleServiceServer) {
	s.RegisterService(&_MapleService_serviceDesc, srv)
}

func _MapleService_EventsStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MapleServiceServer).EventsStream(&mapleServiceEventsStreamServer{stream})
}

type MapleService_EventsStreamServer interface {
	Send(*ResponseEvent) error
	Recv() (*RequestEvent, error)
	grpc.ServerStream
}

type mapleServiceEventsStreamServer struct {
	grpc.ServerStream
}

func (x *mapleServiceEventsStreamServer) Send(m *ResponseEvent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *mapleServiceEventsStreamServer) Recv() (*RequestEvent, error) {
	m := new(RequestEvent)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MapleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "messaging.MapleService",
	HandlerType: (*MapleServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "EventsStream",
			Handler:       _MapleService_EventsStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "service.proto",
}
